name: Build C Program

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile C program
      run: gcc -o my_program my_program.c

    - name: Run the compiled program
      run: ./my_program
